language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran git cmake liblapack-dev swig ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install

script:
  - cd tests
  - make unittests_py examples_code_py
