# Inspiration: https://github.com/edx/configuration/blob/master/.travis.yml
env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - MOSEKLM_LICENSE_FILE=/home/travis/build/testbot/restricted/mosek.lic
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - MATLABPATH=/home/travis/build/matlab-install/matlab
    - MATLAB_ROOT=/home/travis/build/matlab
    - MATLABRELEASE=R2014a
    - SLURP_OS=trusty
    - PYTHONPATH=/usr/local/python
    - TRAVIS_PYTHON_VERSION=2.7
    - NUMPYVERSION=1.11
    - casadi_build_flags="-DWITH_EXTRA_WARNINGS=ON -DWITH_EXTRA_CHECKS=OFF"
   
notifications:
  email: false

notifications:
  email: false

before_script:
  - |
    if [ -n "$KEEP_GOING" ];
    then
      set -e
      set -o pipefail  # otherwise, piping with grep discards exit statuses
    fi

notifications:
  email: false

language: generic

matrix:
  include:
  
    - os: osx
      osx_image: xcode7.3
      env: TESTMODE=minimal SLURP_OS=osx
      compiler: clang
      script:
        - mkdir build
        - pushd build
        - echo $casadi_build_flags
        - bash -c "cmake $casadi_build_flags -DWITH_WERROR=ON -DWITH_PYTHON=ON -DWITH_JSON=ON -DWITH_EXTRA_CHECKS=OFF .."

        - #cmake $casadi_build_flags -DPYTHON_LIBRARY=$CMAKE_PYTHON_LIBRARY -DPYTHON_INCLUDE_DIR=$CMAKE_PYTHON_INCLUDE_DIR -DWITH_PYTHON=ON -DCMAKE_INSTALL_PREFIX=../python_install -DPYTHON_PREFIX=../python_install ..
        - sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
        - locate libgfortran.3.dylib
        - locate libquadmath.0.dylib
        - locate libgcc_s.1.dylib
        - locate libgomp.1.dylib
        - locate libstdc++.6.dylib
        - osx_rpath
        - make VERBOSE=1
        - sudo make install
        - sudo cp $GCC_FULL $QUADMATH_FULL $FORTRAN_FULL $CXX_FULL /usr/local/lib/
        - popd
        - #export PYTHONPATH=$PYTHONPATH:`pwd`/python_install
        - otool -l /Users/travis/miniconda2/envs/condaenv_build/lib/python2.7/site-packages/casadi/_casadi.so
        - echo $DYLD_LIBRARY_PATH
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py && popd

  
branches:
  except:
    - /.*appveyor.*/

before_install:
  - shell_session_update() { :; } # Workaround for travis-ci/travis-ci#6522
  - pushd ../../ && git clone https://github.com/casadi/testbot.git
  - pushd testbot && source recipes/setup.sh && popd
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      osx_gcc49_setup
      export SLURP_OS=osx
      export SLURP_GCC=4.9
      slurp swig_matlab
    else
      sudo apt-get install p7zip-full -y
      sudo apt-get update -qq
      sudo apt-get install -q -y binutils gcc g++ gfortran git cmake liblapack-dev liblapack3 libblas3 coinor-libipopt-dev libmumps-seq-dev libxml2-dev
      if [ $NEEDMATLAB ]
      then
        export SLURP_GCC=4.7
      fi
      slurp swig_matlab
    fi
  - python_setup
  - slurp_common
  - bake_my_library_path
  - ls -al /usr/local/lib
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      slurp cplex
    fi
  - popd

  - pip install github3.py
 
after_failure:
  - pushd /home/travis/build/testbot/ && python -c "from github3 import login;from testbotcredentials import TestBotCredentials;tbc = TestBotCredentials();login(*tbc.github).repository('casadi','casadi').create_comment(sha='$TRAVIS_COMMIT',body='Failure reported by [travis](https://travis-ci.org/casadi/casadi/jobs/$TRAVIS_JOB_ID) in $TRAVIS_COMMIT_RANGE -- $TRAVIS_TEST_RESULT')" && popd


