branches: 
  except:
    - /.*travis.*/

image:
#- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

configuration:
- Release

build_script:
  - set arch= Win64
  - set bitness=64
  - set BITNESS=64
  - set PYTHON_ARCH=64
  - set PYTHON_VERSION=3.7
  - set PYTHONVERSION=37
  - set MINICONDA=C:\Miniconda-x64
  #- git clone https://github.com/casadi/testbot.git
  #- cd testbot && call recipes\setup.bat && cd ..
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n test python=%PYTHON_VERSION% numpy requests
  - activate test
  - cinst -y --no-progress swig
  #- set PYTHONPATH=%PYTHONPATH%;C:\projects\binaries\testbot\helpers
  #- call testbot/fetch_common.bat
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set vsver=15)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set vsver=14)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set vsver=12)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set vsyear=2017)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set vsyear=2015)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set vsyear=2013)
  - echo %vsyear%
  - if "%vsyear%"=="2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\%vsyear%\Community\VC\Auxiliary\Build\vcvars%bitness%.bat" )
  - set CXXFLAGS="-D_CRT_SECURE_NO_WARNINGS"
  - set generator="-GVisual Studio %vsver% %vsyear%%arch%"
  - echo %generator%
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_PYTHON3=ON "-GVisual Studio %vsver% %vsyear%%arch%" -H. -B_builds
  - cmake --build _builds --target install --config Release 
  - cd test/python
  - python alltests.py
