branches: 
  except:
    - /.*travis.*/

environment:
  - matrix:
      - PYTHONVERSION: "2.7"
        PYTHON: "C:\\Miniconda-x64"
        NUMPYVERSION: "1.9"
  
build_script:
  - python --version
  - conda create --yes -n condaenv_build python=$PYTHONVERSION requests pyyaml numpy=$NUMPYVERSION scipy matplotlib
  - conda install --yes -n condaenv_build pip
  - source activate condaenv
  - python --version
  - cmake "-GVisual Studio 12 Win64" -H. -B_builds
  - cmake --build _builds --config "Debug"

