branches: 
  except:
    - /.*travis.*/

install:
  - cinst -y mingw
  - cinst -y mingw-get
  - mingw-get.exe gcc g++ msys-base 
  
build_script:
  - mkdir build
  - cd build
  - cmake "-GMSYS Makefiles" -DWITH_PYTHON=ON ..
  - make
  #- cmake "-GVisual Studio 12 Win64" -H. -B_builds
  #- cmake --build _builds --config "Debug"
